name: Continuous Delivery - Criando CD
on: 
  push:
    branches:
      - main #ou qualquer outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Simulando Continuous Delivery
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          name: projetozipado.zip
          path: |
            **.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: projetozipado.zip
    - name: Display structure of downloaded files
      run: ls -R

